
version: '3.9'

services:

  java_app:
    container_name: java_app
    image: ptishkevich/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgresdocker
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123456789
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: postgresdocker
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
   pgdata: {}
